### ISSUE TITLE
Another feature request

### ISSUE THREAD

**Issue by frentemorao** [EnzoD86/tuya-smart-ir-ac#30]
Hi Enzo

First of all, I would like to point out that your integration works flawlessly.

I was wondering if you could extend the integration to support more devices (TVs, lights...) as far as you can control more devices in the Tuya app 

Thanks in advance
Alejandro from Spain

**Comment by EnzoD86** [comment]
Hi, thank you for your feedback. 
Unfortunately, this integration is not intended to be extended to other devices... also because, as the name itself says, this integration only concerns air conditioning and it would not be correct to integrate other devices.
Bye

**Comment by EnzoD86** [comment]
Hi, I don't know if this request is still valid for you.
But, after thinking about it a lot, I decided to go ahead with this idea!

**Comment by frentemorao** [comment]
Hi Enzo

Great news!!

Don't hesitate if you need anything from me to test the new integration.

Alejandro

________________________________

**Comment by EnzoD86** [comment]
Hi, I released the [beta version](https://github.com/EnzoD86/tuya-smart-ir-ac/releases/tag/2025.3.0-beta)!
The main focus of the integration always remains only the air conditioners; but with this feature it is possible to integrate the other remote controls into home assistant (without creating the scenes on SmartLife or Tuya app),
The devices are added as buttons for each command.

There is a scenario that unfortunately does not work and it is those remote controls that have been added with manual learning button by button (which SmartLife calls DIY device); on these devices the Tuya APIs do not work, probably due to some bug...

I would appreciate it if you could do some tests and let me know what you think.
Thanks

**Comment by Hotelk52339** [comment]
Hello, there is a problem with downloading in HACS

![Image](https://github.com/user-attachments/assets/c25298c2-ac44-4d24-badd-936f164b388e)

**Comment by Hotelk52339** [comment]
Hi @EnzoD86 

Thanks a lot for this awesome integration, it’s an absolute game changer—works perfectly!   
I just downloaded the beta version and tested it with my Samsung TV. All buttons provided by the integration are recognized and work flawlessly.

These are the buttons I got for my Samsung TV:

- 0,1,2,3,4,5,6,7,8,9  
- Back  
- Channel_down  
- Channel_up  
- Confirm  
- Continuous down, left, right, up  
- Display  
- Exit  
- Look back  
- Power  
- Project  
- Screen enlarging  
- Television  
- Tool  
- Tv back  
- TV control volumn  
- TV TV/AV  
- Volume down  
- Volume_up  

Everything works without any issues—great job!

Also, it would be great if the integration could automatically create a complete remote control entity, perhaps even as a `media_player`. This would allow easier control directly through Home Assistant and seamless integration into HomeKit.

Let me know if you need any further testing or additional information!

**Comment by Hotelk52339** [comment]
I wanted to share my working setup using your Tuya IR integration with **Universal Media Player** in Home Assistant. I’m using it with my **Samsung UE32F4500**, and I can track its **power state** via the **Samsung Smart TV integration**, but I **cannot turn it on using this integration**. Instead, I use **Tuya IR** to control the TV  

With this configuration, I get **full control** over the TV while ensuring proper state tracking:  

---

###  My Working Configuration (`configuration.yaml`)  

```yaml
media_player:
  - platform: universal
    name: Samsung TV
    unique_id: samsung_tv_universal
    device_class: tv
    children:
      - media_player.ue32f4500  # Tracks the TV's power state via Samsung Smart TV integration
    state_template: "{{ states('media_player.ue32f4500') }}"
    commands:
      turn_on:
        service: button.press
        target:
          entity_id: button.tv_power
      turn_off:
        service: button.press
        target:
          entity_id: button.tv_power
      volume_up:
        service: button.press
        target:
          entity_id: button.volume_up
      volume_down:
        service: button.press
        target:
          entity_id: button.volume_down
      volume_mute:
        service: button.press
        target:
          entity_id: button.tv_control_volumn
      channel_up:
        service: button.press
        target:
          entity_id: button.channel_up
      channel_down:
        service: button.press
        target:
          entity_id: button.channel_down
    attributes:
      state: media_player.ue32f4500
```

Thanks again for this amazing integration!
