### ISSUE TITLE
In case AC is off nothing works, until I switch it manuallu on

### ISSUE THREAD

**Issue by myemuk** [EnzoD86/tuya-smart-ir-ac#56]
If AC is on everything works as expected, however it is off nothing works until I manually switch it on first.

Possible solution:

1. On every change check if AC is on
2. Turn it on if it is switched off
3. Send set selected state

**Comment by EnzoD86** [comment]
Hi, from the developer console if you try to send this command, does the air conditioner turn on?

```
action: climate.turn_on
target:
  entity_id: your_entity_id
```

**Comment by myemuk** [comment]
Hi, thank you very much for help and your awesome project.
And yes, this command does work and turn AC on.

**Comment by myemuk** [comment]
Thank you for an idea. I've solved this issue by creating automation:

```
alias: Turn AC on
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.lg
    from: "off"
conditions: []
actions:
  - action: climate.turn_on
    metadata: {}
    data: {}
    target:
      device_id: my_device_id
mode: single
```

And now it works perfect. The only wish I have, is it possible to achieve it without any additional automation in home assistant?
